### ISSUE TITLE
Review Session #1

### ISSUE THREAD

**Issue by dlockmal** [hotpeppersec/molecule_ansible#10]
1. Before slide #3... maybe a brief Ansible Introduction
2 Same thing with Molecule before slide 4 since it's there
3. Add a Requirements slide if one isn't provided with your talk.That way people aren't having issues with downloading or installing components before 
    - docker (linux/mac)
    - docker-compose install (linux/mac) 
    - install python requirements locally to run molecule from local env
4. Need to test this all out on Windows.

**Comment by hotpeppersec** [comment]
Cleaned up the slides based on your feedback. Thanks so much for the help @dlockmal 
https://github.com/hotpeppersec/molecule_ansible/pull/11
