### ISSUE TITLE
Test on Windows host

### ISSUE THREAD

**Issue by vladdoster** [hotpeppersec/molecule_ansible#12]
Does this still need to be tested on a Windows host? I could ...

**Comment by hotpeppersec** [comment]
> Does this still need to be tested on a Windows host? I could ...

That would be great! I'd love to see where the issue are and get them cleaned up.

**Comment by vladdoster** [comment]
> > Does this still need to be tested on a Windows host? I could ...
> 
> That would be great! I'd love to see where the issue are and get them cleaned up.

Hi @hotpeppersec,

Do I have enough information in the readme or do I need to know anything ahead of time? Will get on it tonight.

**Comment by hotpeppersec** [comment]
> Do I have enough information in the readme or do I need to know anything ahead of time? Will get on it tonight.

I don't think things will work as-is. There are a few options: 

- nmake: create a windows native Makfile (I think? ok option)
- CMake: create a new Makefile that is cross platform (better option)
- Cygwin: Ask windows users to install Cygwin with certain packages (easiest option but i can't test this one)

Thoughts?

**Comment by vladdoster** [comment]
> > Do I have enough information in the readme or do I need to know anything ahead of time? Will get on it tonight.
> 
> I don't think things will work as-is. There are a few options:
> 
> * nmake: create a windows native Makfile (I think? ok option)
> * CMake: create a new Makefile that is cross platform (better option)
> * Cygwin: Ask windows users to install Cygwin with certain packages (easiest option but i can't test this one)
> 
> Thoughts?

Cmake takes the cake out of those 3. As you said, multiple compilation targets is great.
